"""fix relations

Revision ID: 2798db9d88a7
Revises: fdbf62095ffb
Create Date: 2023-02-26 22:25:49.218669

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '2798db9d88a7'
down_revision = 'fdbf62095ffb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('curator_enrollment_id_fkey', 'curator', type_='foreignkey')
    op.drop_column('curator', 'enrollment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('curator', sa.Column('enrollment_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('curator_enrollment_id_fkey', 'curator', 'enrollment', ['enrollment_id'], ['id'])
    # ### end Alembic commands ###
