"""add screenplay request table

Revision ID: 5fb6ceee1753
Revises: e4dda7f995ee
Create Date: 2023-05-28 22:21:50.967272

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '5fb6ceee1753'
down_revision = 'e4dda7f995ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('screenplay_request',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('screenplay_id', sa.String(length=256), nullable=False),
                    sa.Column('act_id', sa.String(length=256), nullable=False),
                    sa.Column('context', sa.String(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('screenplay_request')
    # ### end Alembic commands ###
