"""add assignment status column

Revision ID: 60fef9007bec
Revises: da279acb1abc
Create Date: 2023-02-28 09:04:03.393186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from sqlalchemy.dialects import postgresql

revision = '60fef9007bec'
down_revision = 'da279acb1abc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    status_enum = postgresql.ENUM('READY_FOR_REVIEW', 'REVIEWED', name='assignmentstatus')
    status_enum.create(op.get_bind())
    op.add_column('assignment', sa.Column('status', sa.Enum('READY_FOR_REVIEW', 'REVIEWED', name='assignmentstatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignment', 'status')
    # ### end Alembic commands ###
