"""add status history table

Revision ID: 749ae495c497
Revises: 6fe8a64962a0
Create Date: 2023-05-21 19:37:46.076303

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '749ae495c497'
down_revision = '6fe8a64962a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment_status_history',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('new_status', sa.Enum('READY_FOR_REVIEW', 'REVIEWED', 'REVIEW_IN_PROGRESS',
                              name='assignmentstatus', native_enum=False), nullable=False),
                    sa.Column('assignment_id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(['assignment_id'], ['assignment.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.execute("ALTER TYPE assignmentstatus ADD VALUE 'REVIEW_IN_PROGRESS'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assignment_status_history')
    # ### end Alembic commands ###
