"""make student nicks unique

Revision ID: 7be639751979
Revises: 749ae495c497
Create Date: 2023-05-21 22:17:39.010012

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '7be639751979'
down_revision = '749ae495c497'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'student', ['telegram_nickname'])
    op.create_unique_constraint(None, 'student', ['telegram_chat_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student', type_='unique')  # type: ignore[arg-type]
    op.drop_constraint(None, 'student', type_='unique')  # type: ignore[arg-type]
    # ### end Alembic commands ###
