"""add context table

Revision ID: 7bf5a873f2bc
Revises: dc514e279a1d
Create Date: 2023-03-17 18:54:20.164751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bf5a873f2bc'
down_revision = 'dc514e279a1d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('screenplay_context',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('screenplay_id', sa.String(length=256), nullable=False),
    sa.Column('data', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('active_screenplay_id', sa.String(length=256), nullable=False))
    op.add_column('user', sa.Column('active_act_id', sa.String(length=256), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'active_act_id')
    op.drop_column('user', 'active_screenplay_id')
    op.drop_table('screenplay_context')
    # ### end Alembic commands ###
