"""male names not required

Revision ID: 7cb63055cd27
Revises: 7de96aea0f36
Create Date: 2023-05-15 21:05:40.227339

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '7cb63055cd27'
down_revision = '7de96aea0f36'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'first_name',
                    existing_type=sa.VARCHAR(length=256),
                    nullable=True)
    op.alter_column('user', 'last_name',
                    existing_type=sa.VARCHAR(length=256),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'last_name',
                    existing_type=sa.VARCHAR(length=256),
                    nullable=False)
    op.alter_column('user', 'first_name',
                    existing_type=sa.VARCHAR(length=256),
                    nullable=False)
    # ### end Alembic commands ###
