"""add message table

Revision ID: 967e92ace33f
Revises: 9c1fd851103c
Create Date: 2023-05-18 09:43:55.537640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '967e92ace33f'
down_revision = '9c1fd851103c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_chat_id', sa.String(length=256), nullable=True),
    sa.Column('from_user_id', sa.String(length=256), nullable=True),
    sa.Column('message', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_message')
    # ### end Alembic commands ###
