"""add rereview column

Revision ID: a9e1612b5757
Revises: d0668d8591d4
Create Date: 2023-06-06 08:34:28.695239

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a9e1612b5757'
down_revision = 'd0668d8591d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment', sa.Column('is_rereview_for', sa.Integer(), nullable=True))
    op.create_foreign_key("assignment_rereview_fk", 'assignment', 'assignment', ['is_rereview_for'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("assignment_rereview_fk", 'assignment', type_='foreignkey')
    op.drop_column('assignment', 'is_rereview_for')
    # ### end Alembic commands ###
