"""add review message id coolumn

Revision ID: d0668d8591d4
Revises: 5fb6ceee1753
Create Date: 2023-06-06 08:18:04.580084

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'd0668d8591d4'
down_revision = '5fb6ceee1753'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment', sa.Column('review_message_id_in_curator_chat', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignment', 'review_message_id_in_curator_chat')
    # ### end Alembic commands ###
