"""add assignment table

Revision ID: da279acb1abc
Revises: 885d9f7214b8
Create Date: 2023-02-27 06:15:30.872522

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'da279acb1abc'
down_revision = '885d9f7214b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('url', sa.String(length=512), nullable=False),
                    sa.Column('student_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assignment')
    # ### end Alembic commands ###
