"""add feedback columnt to assignment

Revision ID: dd4fd7a22c4a
Revises: 78a631d16798
Create Date: 2023-03-02 11:52:22.957492

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'dd4fd7a22c4a'
down_revision = '78a631d16798'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment', sa.Column('curator_feedback', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignment', 'curator_feedback')
    # ### end Alembic commands ###
