"""add auth code for students

Revision ID: e4dda7f995ee
Revises: 7be639751979
Create Date: 2023-05-24 11:20:12.364777

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'e4dda7f995ee'
down_revision = '7be639751979'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('auth_code', sa.String(length=256), nullable=True))
    op.create_unique_constraint(None, 'student', ['auth_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student', type_='unique')  # type: ignore
    op.drop_column('student', 'auth_code')
    # ### end Alembic commands ###
