"""add timepadid/email  columns

Revision ID: eb69c9351fd5
Revises: b88ea67fe382
Create Date: 2023-06-08 07:28:23.526876

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'eb69c9351fd5'
down_revision = 'b88ea67fe382'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('timepad_id', sa.String(length=256), nullable=True))
    op.add_column('student', sa.Column('email', sa.String(length=256), nullable=True))
    op.create_unique_constraint("student_timepad_id_unique", 'student', ['timepad_id'])
    op.create_unique_constraint("student_email_unique", 'student', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("student_timepad_id_unique", 'student', type_='unique')
    op.drop_constraint("student_email_unique", 'student', type_='unique')
    op.drop_column('student', 'email')
    op.drop_column('student', 'timepad_id')
    # ### end Alembic commands ###
