"""remove message column

Revision ID: f1af451f96eb
Revises: 967e92ace33f
Create Date: 2023-05-18 09:48:04.401639

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'f1af451f96eb'
down_revision = '967e92ace33f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_message', 'message')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_message', sa.Column('message', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
